name: Node.js App CI/CD

on:
  # Triggers the workflow on push events to the "master" branch
  push:
    branches:
      - master
  # Triggers the workflow on pull request events to the "master" branch
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build-and-push"
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t code2cloud-nodejs .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Docker Hub
        run: |
          docker tag code2cloud-nodejs ${{ secrets.DOCKER_USERNAME }}/code2cloud-nodejs:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/code2cloud-nodejs:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build-and-push

    steps:
      - name: Deploy to EC2 AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/code2cloud-nodejs:latest
            sudo docker stop code2cloud-nodejs || true
            sudo docker rm code2cloud-nodejs || true
            sudo docker run -d -p 3006:3000 --name=code2cloud-nodejs ${{ secrets.DOCKER_USERNAME }}/code2cloud-nodejs:latest
            sudo docker ps
            sudo docker logs code2cloud-nodejs  # Display container logs
          options: -vvv