# This is a basic workflow to help you get started with Actions
name: Node js App CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push events to the "master" branch
  push:
    branches:
      - master
  # Triggers the workflow on pull request events to the "master" branch
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v3

      - name: Build the docker image
        run: docker build -t code2cloud-nodejs .

      # Runs a single command using the runners shell
      - name: Log in to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      # Runs a set of commands using the runners shell
      - name: push image to docker hub
        run: |
          docker tag code2cloud-nodejs ${{ secrets.DOCKER_USERNAME }}/code2cloud-nodejs:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/code2cloud-nodejs:latest
  # deploy:

  #   runs-on: ubuntu-latest

  #   needs: build-and-push

  #   steps:

  #   - name: Deploy to EC2
  #   uses: 